FROM node:22-alpine

RUN apk -U upgrade \
  && apk add bash --no-cache \
  && npm install npm --global

WORKDIR /app

# Copy package files and install dependencies to leverage Docker cache
COPY client/package.json client/package-lock.json* ./
RUN npm install

# Copy the rest of the client code
COPY client/ .

# The command will be specified in docker-compose to allow for easier debugging

