entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true # For local access to dashboard only

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: ${LETSENCRYPT_EMAIL}
      storage: acme.json
      httpChallenge:
        entryPoint: web
